-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 12:25:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
  `idFuncionario` INT NOT NULL,
  `Funcionáriocol` VARCHAR(45) NULL,
  `Especialidade_idEspecialidade` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Especialidade_idEspecialidade`, `Cargo_idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(80) NOT NULL,
  `ufEstado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`));


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(80) NOT NULL,
  `fk_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX (`fk_idEstado` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idEstado`)
    REFERENCES `mydb`.`estados` (`idEstado`));


-- -----------------------------------------------------
-- Table `mydb`.`unidadesSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidadesSaude` (
  `idUniSaude` INT NOT NULL AUTO_INCREMENT,
  `nomeUniSaude` VARCHAR(80) NOT NULL,
  `enderecoUniSaude` VARCHAR(250) NOT NULL,
  `fk_idCidade` INT NOT NULL,
  PRIMARY KEY (`idUniSaude`),
  INDEX (`fk_idCidade` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idCidade`)
    REFERENCES `mydb`.`cidades` (`idCidade`));


-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nomePessoa` VARCHAR(80) NOT NULL,
  `emailPessoa` VARCHAR(250) NULL,
  `senhaPessoa` VARCHAR(250) NOT NULL,
  `tipoPessoa` VARCHAR(10) NOT NULL,
  `cpfPessoa` VARCHAR(14) NULL DEFAULT NULL,
  `enderecoPessoa` VARCHAR(250) NULL DEFAULT NULL,
  `telPessoa` VARCHAR(15) NULL DEFAULT NULL,
  `dataNascPessoa` DATE NOT NULL,
  `fk_idUniSaude` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX (`fk_idUniSaude` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idUniSaude`)
    REFERENCES `mydb`.`unidadesSaude` (`idUniSaude`));


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `statusPaciente` VARCHAR(20) NOT NULL,
  `alergiaPaciente` VARCHAR(300) NULL,
  `doencaGeneticaPaciente` VARCHAR(300) NULL,
  `telEmergenciaPaciente` VARCHAR(15) NULL DEFAULT NULL,
  `fk_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_paciente_pessoa1_idx` (`fk_idPessoa` ASC),
  CONSTRAINT `fk_paciente_pessoa1`
    FOREIGN KEY (`fk_idPessoa`)
    REFERENCES `mydb`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`processos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`processos` (
  `idProcesso` INT NOT NULL AUTO_INCREMENT,
  `protocoloProcesso` VARCHAR(12) NOT NULL,
  `dataInicialProcesso` DATE NOT NULL,
  `dataFinalProcesso` DATE NOT NULL,
  `fk_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idProcesso`),
  INDEX `fk_processo_paciente1_idx` (`fk_idPaciente` ASC),
  CONSTRAINT `fk_processo_paciente1`
    FOREIGN KEY (`fk_idPaciente`)
    REFERENCES `mydb`.`pacientes` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`procedimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`procedimentos` (
  `idProcedimento` INT NOT NULL AUTO_INCREMENT,
  `nomeProcedimento` VARCHAR(80) NOT NULL,
  `descProcedimento` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idProcedimento`));


-- -----------------------------------------------------
-- Table `mydb`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidades` (
  `idEspecialidade` INT NOT NULL AUTO_INCREMENT,
  `nomeEspecialidade` VARCHAR(80) NOT NULL,
  `descEspecialidade` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idEspecialidade`));


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nomeCargo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCargo`));


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `fk_idPessoa` INT NOT NULL,
  `fk_idEspecialidade` INT NULL DEFAULT NULL,
  `fk_idCargo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX (`fk_idPessoa` ASC),
  INDEX (`fk_idEspecialidade` ASC),
  INDEX (`fk_idCargo` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idPessoa`)
    REFERENCES `mydb`.`pessoas` (`idPessoa`),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idEspecialidade`)
    REFERENCES `mydb`.`especialidades` (`idEspecialidade`),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idCargo`)
    REFERENCES `mydb`.`cargos` (`idCargo`));


-- -----------------------------------------------------
-- Table `mydb`.`processosProc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`processosProc` (
  `idProcessoProc` INT NOT NULL AUTO_INCREMENT,
  `dataHoraProcessoProc` VARCHAR(5) NOT NULL,
  `statusHistorico` VARCHAR(20) NOT NULL,
  `remedioProcessoProc` VARCHAR(250) NULL DEFAULT NULL,
  `obsMedicas` VARCHAR(250) NULL DEFAULT NULL,
  `fk_idProcesso` INT NOT NULL,
  `fk_idProcedimento` INT NOT NULL,
  `fk_idUniSaude` INT NOT NULL,
  `fk_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idProcessoProc`),
  INDEX (`fk_idProcedimento` ASC),
  INDEX `fk_processoProc_unidadeSaude1_idx` (`fk_idUniSaude` ASC),
  INDEX `fk_processoProc_funcionario1_idx` (`fk_idFuncionario` ASC),
  INDEX `fk_processoProc_processo1_idx` (`fk_idProcesso` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idProcedimento`)
    REFERENCES `mydb`.`procedimentos` (`idProcedimento`),
  CONSTRAINT `fk_processoProc_unidadeSaude1`
    FOREIGN KEY (`fk_idUniSaude`)
    REFERENCES `mydb`.`unidadesSaude` (`idUniSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processoProc_funcionario1`
    FOREIGN KEY (`fk_idFuncionario`)
    REFERENCES `mydb`.`funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processoProc_processo1`
    FOREIGN KEY (`fk_idProcesso`)
    REFERENCES `mydb`.`processos` (`idProcesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exames` (
  `idExame` INT NOT NULL,
  `nomeExame` VARCHAR(80) NOT NULL,
  `unidadeExame` VARCHAR(80) NOT NULL,
  `arquivoExame` BLOB NULL,
  `dataExame` DATE NOT NULL,
  `fk_idProcessoProc` INT NOT NULL,
  PRIMARY KEY (`idExame`),
  INDEX `fk_exame_processoProc1_idx` (`fk_idProcessoProc` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`fk_idProcessoProc`)
    REFERENCES `mydb`.`processosProc` (`idProcessoProc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
